version: "3"
services:
  mysql:
    image: mysql:5.7.27
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
  redis:
    image: redis:latest
  vueblog:
    image: vueblog:latestcompose
    build: .
    ports:
      - 8081:8081
    depends_on:
      - mysql
      - redis
